export interface InternTask {
  title: string;
  description: string;
  difficulty: "beginner" | "intermediate" | "advanced";
  category: "synthetic-data" | "mock-apis" | "local-db" | "code-review" | "docs-research" | "git-workflow";
  learningObjective: string;
  safeEnvironment: string;
  expectedOutput: string;
  resources: string[];
}

export const INTERN_TASKS: InternTask[] = [
  {
    title: "Set up a local dev environment",
    description: "Clone the repo, install dependencies, run `npm run dev` and confirm the dashboard loads.",
    difficulty: "beginner",
    category: "git-workflow",
    learningObjective: "Practice cloning a repo, installing dependencies, and running a dev server for the first time.",
    safeEnvironment: "Your local machine — no production access needed. All config is in `.env.local`.",
    expectedOutput: "A running dev server at http://localhost:3000 showing the dashboard.",
    resources: ["README.md", "AGENTS.md", "npm install docs"],
  },
  {
    title: "Write a test for an ingester",
    description: "Add a unit test for the Hacker News ingester that verifies URL parsing works correctly.",
    difficulty: "intermediate",
    category: "mock-apis",
    learningObjective: "Learn how to write a mock-based unit test for a data ingestion pipeline.",
    safeEnvironment: "Use a local test runner (`vitest` or `jest`) — no external services required.",
    expectedOutput: "A passing test file under `src/ingesters/hn/__tests__/` that mocks fetch and validates parsing.",
    resources: ["src/ingesters/hn/index.ts", "Existing test patterns in the project"],
  },
  {
    title: "Add a new RSS feed source",
    description: "Research a relevant blog/RSS feed, add it to the ingester config, and run `npm run ingest` to verify.",
    difficulty: "intermediate",
    category: "docs-research",
    learningObjective: "Practice researching relevant sources, extending config files, and running the ingestion pipeline.",
    safeEnvironment: "Add the feed to the local config — it only affects your local database.",
    expectedOutput: "A new entry in `src/ingesters/rss/feeds.ts` with the feed URL and category, plus items appearing in the dashboard.",
    resources: ["src/ingesters/rss/feeds.ts", "docs/README.md (Navigation Map → Add an RSS feed source)"],
  },
  {
    title: "Build a chart for feed volume",
    description: "Create a simple bar chart showing how many items per source were ingested in the last 7 days.",
    difficulty: "advanced",
    category: "local-db",
    learningObjective: "Learn how to query aggregated data and render it with Nivo charts.",
    safeEnvironment: "Use the local Supabase project — no production data involved.",
    expectedOutput: "A new chart component at `components/briefing/feed-volume-chart.tsx` integrated into the homepage.",
    resources: ["components/briefing/feed-breakdown.tsx (reference)", "@nivo/bar docs", "src/lib/analytics.ts"],
  },
  {
    title: "Review and tag unclassified entries",
    description: "Go through entries with category 'general' and assign appropriate tags/categories.",
    difficulty: "beginner",
    category: "docs-research",
    learningObjective: "Understand the data model and practice categorizing content accurately.",
    safeEnvironment: "Work on local data — run a script that queries `feed_items` with `category='general'`.",
    expectedOutput: "SQL UPDATE statements or a script that re-categorizes at least 20 entries.",
    resources: ["src/db/schema.ts", "Supabase SQL Editor", "docs/supabase-schema.sql"],
  },
  {
    title: "Review a pull request for common bugs",
    description: "Spot missing error handling, incorrect async patterns, and logic errors in a sample PR diff.",
    difficulty: "intermediate",
    category: "code-review",
    learningObjective: "Develop code review skills by identifying real-world bugs in a controlled diff.",
    safeEnvironment: "A mock PR diff on a practice branch — nothing is deployed.",
    expectedOutput: "A written review listing 3-5 bugs found, with explanations and suggested fixes.",
    resources: ["Sample PR diff (provided)", "Code review checklist (docs/)"],
  },
  {
    title: "Write a synthetic health check",
    description: "Build a script that pings `/api/feed` and alerts if the response is not 200 or takes longer than 500ms.",
    difficulty: "intermediate",
    category: "mock-apis",
    learningObjective: "Learn how to build a simple health-check monitor using the existing API routes.",
    safeEnvironment: "Runs against your local dev server — no infrastructure impact.",
    expectedOutput: "A `scripts/health-check.ts` script that logs pass/fail status with response times.",
    resources: ["app/api/feed/route.ts", "node:fetch docs", "Existing scripts/ patterns"],
  },
  {
    title: "Replace a live RSS feed with a mock",
    description: "Create a local mock server that returns fixture RSS XML so tests don't depend on external services.",
    difficulty: "advanced",
    category: "mock-apis",
    learningObjective: "Understand dependency isolation and test fixture creation for external API calls.",
    safeEnvironment: "A local mock server — no external services are touched.",
    expectedOutput: "A `scripts/mock-rss-server.ts` that serves fixture XML and a test proving the ingester works with it.",
    resources: ["src/ingesters/rss/index.ts", "node:http docs", "Sample fixture XML"],
  },
  {
    title: "Query the DB for untagged entries",
    description: "Write a SQL query to find all `feed_items` where `tags IS NULL`, then update them with appropriate labels.",
    difficulty: "beginner",
    category: "local-db",
    learningObjective: "Practice basic SQL queries — SELECT, UPDATE, and filtering with NULL checks.",
    safeEnvironment: "Local Supabase project — only your local data is affected.",
    expectedOutput: "SQL queries that find and update untagged entries, logged to console.",
    resources: ["docs/supabase-schema.sql", "Supabase SQL Editor"],
  },
  {
    title: "Create seed fixtures for the feed table",
    description: "Write a script that generates 50 fake `feed_items` rows for testing the feed UI with realistic data.",
    difficulty: "intermediate",
    category: "synthetic-data",
    learningObjective: "Practice generating synthetic data that matches the schema for UI testing.",
    safeEnvironment: "Inserts into local database only — no production data involved.",
    expectedOutput: "A `scripts/seed-feed.ts` script that inserts 50 rows with varied sources, categories, and dates.",
    resources: ["docs/supabase-schema.sql", "src/db/schema.ts (seed patterns)"],
  },
  {
    title: "Practice a rebase workflow",
    description: "Create a feature branch, make 3 commits, then rebase onto main and resolve a simulated conflict.",
    difficulty: "beginner",
    category: "git-workflow",
    learningObjective: "Master git rebase and conflict resolution in a safe environment.",
    safeEnvironment: "A practice branch in the local repo — nothing is pushed to remote.",
    expectedOutput: "A clean commit history after rebase, with conflicts resolved.",
    resources: ["Git rebase docs", "Practice repo exercises"],
  },
  {
    title: "Investigate a spike in 500 errors",
    description: "Analyze a set of fake application logs to find the root cause of a sudden increase in server errors.",
    difficulty: "intermediate",
    category: "local-db",
    learningObjective: "Practice log analysis — parsing timestamps, grouping by error code, identifying patterns.",
    safeEnvironment: "Uses the existing log analysis dashboard with synthetic log data.",
    expectedOutput: "A brief root-cause report identifying the failing endpoint and time window.",
    resources: ["/logs page", "src/lib/log-parser.ts", "Sample log file"],
  },
  {
    title: "Respond to a simulated outage",
    description: "The feed stopped updating. Investigate the ingester logs, identify the failure, and write a post-mortem.",
    difficulty: "advanced",
    category: "code-review",
    learningObjective: "Practice incident response — triage, root cause analysis, and post-mortem writing.",
    safeEnvironment: "A simulated outage scenario — no real services are affected.",
    expectedOutput: "A post-mortem document with timeline, root cause, and action items.",
    resources: ["Ingester logs", "Incident response template"],
  },
];
